### ISSUE TITLE
Problem importing dates

### ISSUE THREAD

**Issue by j0hnm4r5** [wwilsman/js-yaml-loader#1]
When trying to import a date from a YAML file, like this:

```yaml
education: 

    - name: University of Oklahoma
      instAbbr: UO
      location: Oklahoma City, OK
      degree: Bachelors of Information Technology
      degAbbr: BIT
      startDate: 2011-06-01
      endDate: 2014-01-01
      curriculum: 
              - DB1101 - Basic SQL
              - CS2011 - Java Introduction
```

Webpack spits out the error:

```
ERROR in ./import/EXAMPLE.yaml
Module parse failed: Invalid number (42:23)
You may need an appropriate loader to handle this file type.
|        degree: 'Bachelors of Information Technology',
|        degAbbr: 'BIT',
|        startDate: 2011-06-01T00:00:00.000Z,
|        endDate: 2014-01-01T00:00:00.000Z,
|        curriculum: [ 'DB1101 - Basic SQL', 'CS2011 - Java Introduction' ] } ],
 @ ./src/index.js 27:11-44
 @ multi (webpack)-dev-server/client?http://localhost:4000 ./src/index.js
```

Wrapping the dates in a quotes (to turn them into strings) works perfectly fine.

Attempting the same file with [yaml-loader](https://www.npmjs.com/package/yaml-loader) returns no issues, and imports the date as expected (i.e., as a DateTime object in the js object).
